"""Few changes v1

Revision ID: 9642bf6b3db1
Revises: 
Create Date: 2025-05-10 11:53:22.713982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9642bf6b3db1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('http_code', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('Error_details', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.drop_column('Error_details')
        batch_op.drop_column('http_code')

    # ### end Alembic commands ###
